### ISSUE TITLE
[question] why is config.json in .gitignore?

### ISSUE THREAD

**Issue by pokuwagata** [twitterdev/twitter-webhook-boilerplate-node#3]
Hi, 
why is config.json in .gitignore?
I think config.json should be commited for deploy to Heroku.

**Comment by jcipriano** [comment]
It's in .gitignore so that API keys are not commited to source control and visible to everyone.

Without a config.js, Heroku will pull the config from env variables as described in step #3 of **Deploy to Heroku (optional)** section.

This app uses the the package [nconf](https://www.npmjs.com/package/nconf) for hierarchical configuration.
