### ISSUE TITLE
{"errors":[{"code":32,"message":"Could not authenticate you."}]}

### ISSUE THREAD

**Issue by rajan-g** [twitterdev/twitter-webhook-boilerplate-node#6]
While I try to subscribe webhook I am getting error 

> **{"errors":[{"code":32,"message":"Could not authenticate you."}]}**

My basic need is I want to receive all my message by webhook. 
I used node **example_scripts/webhook_management/create-webhook-config.js**  with my keys.

**Comment by patrickd-** [comment]
We're experiencing the same issue

related:
- https://twittercommunity.com/t/using-account-activity-api/99226/6
- https://twittercommunity.com/t/webhooks-could-not-authenticate-you-error/91214/6
- https://twittercommunity.com/t/webhook-error-code-32-while-trying-to-create-a-webhook/101360/14
- https://twittercommunity.com/t/account-activity-api-errors-code-200-message-forbidden-or-code-32-message-could-not-authenticate-you/101392/2
- https://twittercommunity.com/t/webhook-creation-fail-with-code-32-message-could-not-authenticate-you/100429

**Comment by xjose97x** [comment]
Was this fixed @patrickd-  @rajan-g

**Comment by patrickd-** [comment]
See https://twittercommunity.com/t/using-account-activity-api/99226/9

For us this was not a problem with this library but the fact that our Account did not actually have access to this new API. It was confusing because we were not able to fill out the application form that the documentation pointed to as it would always just redirect us back to the dashboard.

If you have the same issue you'll have to report it in the twitter community forum

**Comment by sbsashu** [comment]
[ { code: 32, message: 'Could not authenticate you.' } ] for get all follower from twitter api

**Comment by andypiper** [comment]
> [ { code: 32, message: 'Could not authenticate you.' } ] for get all follower from twitter api

Is this related to this project? You should use twittercommunity.com for general developer API questions.

**Comment by AsaoluElijah** [comment]
I had a similar problem, regenerating the authentication keys from twitter developer platform solved it for me.
